calibration_frames: 40
camera_matrix:
- - 519.251443206308
  - 0.0
  - 316.49408414149354
- - 0.0
  - 171.47788953271998
  - 211.28837267632412
- - 0.0
  - 0.0
  - 1.0
dist_coeffs:
- - -0.10591681036657939
  - 0.7789954398604209
  - 0.19384888077181628
  - -0.009544953053091679
  - -0.3830583027111288
image_size:
- 640
- 480
timestamp: '20251220_203936'
